# Generated by Django 4.2.7 on 2024-01-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='autor',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AddField(
            model_name='model1',
            name='nazev',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AddField(
            model_name='model1',
            name='prispevek',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
