# Generated by Django 4.2.7 on 2024-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_model1_autor_model1_nazev_model1_prispevek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='prispevek',
            field=models.TextField(null=True),
        ),
    ]
